#2024-11-07_Inburgeringstermijn Gemeente_rev4609
openapi: 3.0.0
info:
  title: Inburgeringstermijn API
  description: 'Met deze API kan de inburgeringstermijn geraadpleegd worden. '
  version: 1.0.0
paths:
  /personen/{bsn}/inburgeringstermijn:
    get:
      tags:
      - Inburgeringstermijn
      summary: Raadplegen van de actuele inburgeringstermijn van een persoon.
      operationId: getInburgeringstermijnByBsn
      parameters:
      - $ref: '#/components/parameters/Bsn'
      - $ref: '#/components/parameters/BerichtId'
      - $ref: '#/components/parameters/Bron'
      - $ref: '#/components/parameters/Doel'
      responses:
        "200":
          description: OK
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inburgeringstermijn'
        "400":
          description: Fout verzoek
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
        "403":
          description: Niet geautoriseerd
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
        "404":
          description: Niet gevonden
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
        "500":
          description: Internal Server Error
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
        "503":
          description: Service Unavailable
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
  /personen/{bsn}/inburgeringstermijn/historie:
    get:
      tags:
      - Inburgeringstermijn
      summary: Raadplegen van de mutatiehistorie van een persoon zijn Inburgeringstermijn.
      operationId: getInburgeringstermijnhistorieByBsn
      parameters:
      - $ref: '#/components/parameters/Bsn'
      - $ref: '#/components/parameters/BerichtId'
      - $ref: '#/components/parameters/Bron'
      - $ref: '#/components/parameters/Doel'
      responses:
        "200":
          description: OK
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Inburgeringstermijnhistorie'
        "400":
          description: Fout verzoek
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
        "403":
          description: Niet geautoriseerd
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
        "404":
          description: Niet gevonden
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
        "500":
          description: Internal Server Error
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
        "503":
          description: Service Unavailable
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
  /verlengingsgronden:
    get:
      tags:
      - Inburgeringstermijn
      summary: 'Raadplegen van de verlengingsgronden. '
      operationId: getVerlengingsgronden
      parameters:
      - $ref: '#/components/parameters/BerichtId'
      - $ref: '#/components/parameters/Bron'
      - $ref: '#/components/parameters/Doel'
      responses:
        "200":
          description: OK
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Verlengingsgrond'
        "400":
          description: Fout verzoek
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
        "500":
          description: Internal Server Error
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
        "503":
          description: Service Unavailable
          headers:
            API-Version:
              description: Volledige versienummer van de gebruikte API
              required: true
              schema:
                maxLength: 255
                minLength: 1
                pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
                  d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
                  +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
                type: string
                description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH),\
                  \ dat gebruikt wordt om de aard van wijzigingen in software aan\
                  \ te geven."
components:
  schemas:
    Inburgeringstermijn:
      required:
      - einddatum
      - startdatum
      type: object
      properties:
        startdatum:
          type: string
          description: De datum die het begin van de periode aangeeft (inclusief).
          format: date
        einddatum:
          type: string
          description: De datum die het einde van de periode aangeeft (exclusief).
          format: date
        wijzigingsdatum:
          type: string
          description: Algemeen gegevenstype voor het vastleggen van een datum.
          format: date
        verlengingsgrondcode:
          maxLength: 10
          minLength: 1
          type: string
          description: "De code van verlengingsgronden comform het keteninformatiemodel.\
            \ Dit bestaat uit een ciijfer en/of eventueel een letter.; Verbijzondering\
            \ van: Nadere beschrijving"
        verlengingsgrondomschrijving:
          maxLength: 200
          minLength: 1
          type: string
          description: "De gronden waarom de Inburgeringstermijn wordt aangepast conform\
            \ het keteninfomratiemodel. ; Verbijzondering van: Nadere beschrijving "
    Inburgeringstermijnhistorie:
      type: object
      properties:
        einddatum:
          type: string
          description: De datum die het einde van de periode aangeeft (exclusief).
          format: date
        wijzigingsdatum:
          type: string
          description: Algemeen gegevenstype voor het vastleggen van een datum.
          format: date
        verlengingsgrondcode:
          maxLength: 10
          minLength: 1
          type: string
          description: "De code van verlengingsgronden comform het keteninformatiemodel.\
            \ Dit bestaat uit een ciijfer en/of eventueel een letter.; Verbijzondering\
            \ van: Nadere beschrijving"
        verlengingsgrondomschrijving:
          maxLength: 200
          minLength: 1
          type: string
          description: "De gronden waarom de Inburgeringstermijn wordt aangepast conform\
            \ het keteninfomratiemodel. ; Verbijzondering van: Nadere beschrijving "
    Verlengingsgrond:
      required:
      - code
      - omschrijving
      type: object
      properties:
        code:
          maxLength: 10
          minLength: 1
          type: string
          description: "De code van verlengingsgronden comform het keteninformatiemodel.\
            \ Dit bestaat uit een ciijfer en/of eventueel een letter.; Verbijzondering\
            \ van: Nadere beschrijving"
        omschrijving:
          maxLength: 200
          minLength: 1
          type: string
          description: "De gronden waarom de Inburgeringstermijn wordt aangepast conform\
            \ het keteninfomratiemodel. ; Verbijzondering van: Nadere beschrijving "
  parameters:
    API-Version:
      name: API-Version
      in: header
      description: Volledige versienummer van de gebruikte API
      required: true
      schema:
        maxLength: 255
        minLength: 1
        pattern: "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\\
          d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\\
          +([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
        type: string
        description: "Een versienummer met drie onderdelen (MAJOR.MINOR.PATCH), dat\
          \ gebruikt wordt om de aard van wijzigingen in software aan te geven."
    BerichtId:
      name: berichtId
      in: header
      description: Unieke identificatie ten aanzien van traceerbaarheid en beheer
        op het verzoek- en antwoordbericht. Het berichtId wordt bij elk verzoekbericht
        willekeurig gegenereerd. In het antwoordbericht wordt vervolgens hetzelfde
        berichtId teruggegeven als het verzoekbericht.
      required: true
      schema:
        maxLength: 36
        minLength: 36
        type: string
        description: Universeel unieke identificatie in hexadecimale getallen.
        format: uuid
    Bron:
      name: bron
      in: header
      description: Bron organisatie waar het bericht vandaan komt.
      required: true
      schema:
        maxLength: 20
        minLength: 20
        type: string
        description: Het OIN (Organisatie-identificatienummer) is een uniek identificerend
          nummer dat gebruikt wordt door overheidspartijen of organisaties met een
          publieke taak in de digitale communicatie met andere publieke of private
          partijen
    Bsn:
      name: bsn
      in: path
      required: true
      schema:
        maxLength: 9
        minLength: 9
        pattern: "\\d{9}"
        type: string
        description: Het burgerservicenummer (BSN) is het nummer dat de natuurlijke
          persoon uniek identificeert in overheidsadministraties.
    Doel:
      name: doel
      in: header
      description: Doel organisatie waar het bericht voor bestemd is.
      required: true
      schema:
        maxLength: 20
        minLength: 20
        type: string
        description: Het OIN (Organisatie-identificatienummer) is een uniek identificerend
          nummer dat gebruikt wordt door overheidspartijen of organisaties met een
          publieke taak in de digitale communicatie met andere publieke of private
          partijen
